/**
 * Tailwind CSS configuration file.
 * Consolidates the custom color palette and other theme extensions used across the project.
 */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./pages/**/*.html",
    "./js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d5e7d8",
        "dusty-rose": "#7C6C77",
        "teal-blue": "#56A3A6",
        "surface-container-low": "#f5f3f1",
        "surface-dim": "#dbdad8",
        "on-surface-variant": "#434843",
        "primary-container": "#223127",
        "secondary": "#186c41",
        "on-secondary-fixed": "#00210f",
        "background": "#fbf9f7",
        "primary": "#0d1c13",
        "on-surface": "#1b1c1b",
        "on-error-container": "#93000a",
        "soft-parchment": "#F1DAC4",
        "on-secondary-fixed-variant": "#00522d",
        "on-primary-container": "#88998c",
        "inverse-on-surface": "#f2f0ee",
        "surface-container-highest": "#e4e2e0",
        "on-background": "#1b1c1b",
        "primary-fixed-dim": "#b9cbbc",
        "secondary-fixed": "#a4f4bd",
        "outline-variant": "#c3c8c2",
        "deep-pine": "#223127",
        "surface-bright": "#fbf9f7",
        "on-tertiary-fixed": "#291617",
        "surface-tint": "#526256",
        "tertiary-fixed": "#fddadb",
        "secondary-container": "#a1f1bb",
        "surface-variant": "#e4e2e0",
        "tertiary": "#261415",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#101f15",
        "inverse-primary": "#b9cbbc",
        "surface-container-high": "#eae8e6",
        "secondary-fixed-dim": "#88d7a3",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#30302f",
        "error": "#ba1a1a",
        "surface": "#fbf9f7",
        "on-primary-fixed-variant": "#3b4a3f",
        "on-tertiary-fixed-variant": "#584142",
        "on-tertiary": "#ffffff",
        "surface-container": "#efedeb",
        "on-tertiary-container": "#ac8e8f",
        "on-secondary-container": "#1f7045",
        "tertiary-fixed-dim": "#e0bfbf",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#3d2829",
        "outline": "#737873",
        "sage-green": "#68B684",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        "container-max": "1280px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        base: "8px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-sm": ["Roboto Flex"],
        "label-lg": ["Roboto Flex"],
        "label-md": ["Roboto Flex"],
        "body-sm": ["Source Sans 3"],
        "display-lg": ["Roboto Flex"],
        "body-md": ["Source Sans 3"],
        "body-lg": ["Source Sans 3"],
        "headline-md": ["Roboto Flex"],
        "headline-lg": ["Roboto Flex"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
